package com.xafdy.model;

public class StudentFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_file.id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_file.student_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_file.teacher_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    private Integer teacherId;
    private String teacherName;
    private String studentName;
    public String getStudentName() {
		return studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_file.path
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    private String path;

    public String getTeacherName() {
		return teacherName; 
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_file.id
     *
     * @return the value of student_file.id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_file.id
     *
     * @param id the value for student_file.id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_file.student_id
     *
     * @return the value of student_file.student_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_file.student_id
     *
     * @param studentId the value for student_file.student_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_file.teacher_id
     *
     * @return the value of student_file.teacher_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_file.teacher_id
     *
     * @param teacherId the value for student_file.teacher_id
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_file.path
     *
     * @return the value of student_file.path
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_file.path
     *
     * @param path the value for student_file.path
     *
     * @mbg.generated Sat May 25 09:59:19 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}